from app.core.database import Base
from app.models.user import User
from app.models.category import Category
from app.models.movie import Movie
from app.models.comment import Comment
from app.models.history import WatchHistory
from app.models.payment import Payment
from app.models.watchlist import Watchlist
from app.models.movie_view import MovieView